mkdir Data

xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\AccessStash.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\ArbitrationLabel.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\AsyncHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\BehaviorHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\BuildAuditInfo.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\BuildAuditTip.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CacheHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Calendar.ChangedForTest.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Calendar.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CallSBContainer.ModifiedForDebugging.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CallSBContainer.ModifiedForTesting.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CallSBContainer.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CaseAge.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CaseOrdersSBContainer.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\cDisplayOrder.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\cDisplayOrderDlg.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\cLocationPicker.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CodeMappingHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CodeSearchDlg.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Collection.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Common.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Common3.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CopyToClipboard.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CreateCaseNbrSrchIndex.ChangedForTest.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\CreateCaseNbrSrchIndex.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\cStack.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\DialogUI.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\DisableSelect.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\DlgControlHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\DLValidate.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\DocSecGroupHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\DOMDocVersion.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\ErrorSelectContModal.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\ErrorSelectModal.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\FirearmPermitSBContainer.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\FullTextSearch.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\GenericAuditInformation.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\GenericAutoNumber.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\GenericCollection.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\GiveFocus.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\IIf.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Item.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\JavascriptInterop.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\LicenseKey.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MaintenanceReport.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MarkCurrentLaunch.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MeridianTable.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MessageArea.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MNDefAgeVerification.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\ModalMessageBox.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MouseButtonEvents.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MRUKeyList.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\MultiParty.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\NumberToText.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\ObjectExists.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\OFMAware.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\OptionBuilder.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\OrgChart.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PageDisabler.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Pager.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Paging.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PartyCopyUtility.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PartyMatch.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PartySelector.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PartySelector2.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PaymentSchedules.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PostCallbackSetInitialFocus.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Printer.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\PromptPageNumber.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\QueryString.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Scriptlets.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Search.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\SecurityGroupHelper.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\SelectCode.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\selectTable2.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\SetControl.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\SilverlightDownloadSupport.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\SilverlightHost.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\SilverlightSupport.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\StashedCodes.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\TabsController.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\tabTimeTracking.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\TextEditor.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\TreeViewLoader.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\UriBuilder.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Validate.ChangedForTest.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Validate.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\VerticalTabController.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\VictimProtOrderUI.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\VictimRestitutionUI.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\ViewSource.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\Warning.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\WebService.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\WitnessEvidenceUI.vbs .\Data /Y /I
xcopy ..\..\cj-odyssey_mainline\Webs\Common\Scripts\XslUtility.vbs .\Data /Y /I
